### PR TITLE
added BRIDGED network mode

### PR DESCRIPTION
**Pull request by hamdiz0**
added BRIDGED network configuration along with the existing NAT one 
configured the compatability for both windows and linux with a simple if else function
tested both BRIDGED and NAT network modes before commiting changes

### CODE REVIEW

**Comment by hamdiz0** [comment]
kindly merge if possible

**Comment by vancanhuit** [comment]
Hi @hamdiz0, thanks for your contribution. It looks good to me, but I have a question: What is your use case to use a public network? My intention for this setup is to just have a playground in a private network for experimental and learning.

**Comment by hamdiz0** [comment]
Thanks for replying, some times its just a bit  too complicatited to ssh into a virtual machine with NAT private network configuration.
I also find that having the ability to switch between BRIDGED and NAT is certainly more flexible.

**Comment by hamdiz0** [comment]
Thanks brother !!!

**Pull request merged**
